# Generated by Django 4.2.27 on 2026-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('completed_services', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
